name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04 # or ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
         python-version: 3.12
    - run: |
        pip install pyodide-build>=0.28.0
        echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
    - uses: mymindstorm/setup-emsdk@v14
      with:
         version: ${{ env.EMSCRIPTEN_VERSION }}
    - run: pyodide build
    - uses: actions/upload-artifact@v4
      with:
        path: pyjarsigner/dist
